language: java
#install: true
dist: trusty

jdk:
  - openjdk8
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

jobs:
  include:
    - language: java
      script:
        - ./gradlew clean build test jacocoTestReport
        - sonar-scanner
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      addons:
        sonarcloud:
          organization: oleg-cherednik
          token:
            secure: "83da2cd10b1ed3149b37ce695af1955ced6b4e18"
    - language: android
      android:
        components:
          - android-30
      script:
        - ./gradlew clean build test
    - language: android
      android:
        components:
          - android-18
      script:
        - ./gradlew clean build test
